In [52]:
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from keras.optimizers import Nadam, SGD

In [172]:
from numpy import array
from scipy.stats.mstats import gmean

In [117]:
data = pd.read_csv('data.csv',header=[0])

In [27]:
data=data.drop('Date',axis=1)

In [28]:
for p in data.columns.values:
    data[p]=data[p]-min(data[p])
    data[p]=data[p]/(max(data[p])/2)-1


In [119]:
data

period       Date  aws_rev     amzn  amzn_rev  gcp_rev  alph_rev  \
0       8  30-Sep-18     6679  2003.00     56580     4640     33740   
1       7  30-Jun-18     6105  1699.80     52890     4425     32657   
2       6  31-Mar-18     5442  1447.34     51040     4354     31146   
3       5  31-Dec-17     5133  1169.47     60500     4687     32323   
4       4  30-Sep-17     4584   961.35     43740     3590     27722   
5       3  30-Jun-17     4100   968.00     37960     3241     26010   
6       2  31-Mar-17     3661   886.54     35710     3207     24750   
7       1  31-Dec-16     3536   749.87     43740     3403     26064   

   azure_rev  msft_rev  
0       8567     29084  
1       9606     30085  
2       7896     26819  
3       7795     28918  
4       6922     24538  
5       7822     25605  
6       6730     23212  
7       6758     25826

In [30]:
X=array(data[['amzn_rev','amzn','gcp_rev','alph_rev','azure_rev','msft_rev']])

In [31]:
Y=array(data[['aws_rev']])

In [33]:
Y

array([[ 1.        ],
       [ 0.63474388],
       [ 0.21285396],
       [ 0.01622654],
       [-0.33312122],
       [-0.64110722],
       [-0.92045816],
       [-1.        ]])

In [178]:
model=Sequential()
shapex = X[0].shape
model.add(Dense(shapex[0],input_shape=shapex,activation='selu'))
model.add(Dense(int(gmean([shapex[0],1])),activation='selu'))
model.add(Dense(1,activation='sigmoid'))


In [90]:
nadam = Nadam(lr=.00000001)
sgd = SGD(lr=.0001)
model.compile(optimizer=nadam,loss='mae')

In [91]:
model.fit(X[4:],Y[4:],epochs=5000)

Epoch 1/500
4/4 [==============================] - 1s 230ms/step - loss: 6.5565e-07
Epoch 2/500
4/4 [==============================] - 0s 873us/step - loss: 3.8743e-07
Epoch 3/500
4/4 [==============================] - 0s 1ms/step - loss: 3.8743e-07
Epoch 4/500
4/4 [==============================] - 0s 937us/step - loss: 2.9802e-07
Epoch 5/500
4/4 [==============================] - 0s 1ms/step - loss: 2.4587e-07
Epoch 6/500
4/4 [==============================] - 0s 1ms/step - loss: 2.0117e-07
Epoch 7/500
4/4 [==============================] - 0s 2ms/step - loss: 1.5646e-07
Epoch 8/500
4/4 [==============================] - 0s 683us/step - loss: 1.5646e-07
Epoch 9/500
4/4 [==============================] - 0s 980us/step - loss: 1.5646e-07
Epoch 10/500
4/4 [==============================] - 0s 3ms/step - loss: 1.3411e-07
Epoch 11/500
4/4 [==============================] - 0s 2ms/step - loss: 1.4901e-07
Epoch 12/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0431e-07
Epo

Epoch 99/500
4/4 [==============================] - 0s 893us/step - loss: 5.9605e-08
Epoch 100/500
4/4 [==============================] - 0s 705us/step - loss: 3.7253e-08
Epoch 101/500
4/4 [==============================] - 0s 627us/step - loss: 5.9605e-08
Epoch 102/500
4/4 [==============================] - 0s 742us/step - loss: 3.7253e-08
Epoch 103/500
4/4 [==============================] - 0s 590us/step - loss: 5.9605e-08
Epoch 104/500
4/4 [==============================] - 0s 740us/step - loss: 3.7253e-08
Epoch 105/500
4/4 [==============================] - 0s 767us/step - loss: 5.9605e-08
Epoch 106/500
4/4 [==============================] - 0s 751us/step - loss: 3.7253e-08
Epoch 107/500
4/4 [==============================] - 0s 641us/step - loss: 5.9605e-08
Epoch 108/500
4/4 [==============================] - 0s 3ms/step - loss: 3.7253e-08
Epoch 109/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 110/500
4/4 [==============================] - 0s 1ms

Epoch 196/500
4/4 [==============================] - 0s 745us/step - loss: 3.7253e-08
Epoch 197/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 198/500
4/4 [==============================] - 0s 975us/step - loss: 3.7253e-08
Epoch 199/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 200/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 201/500
4/4 [==============================] - 0s 694us/step - loss: 5.9605e-08
Epoch 202/500
4/4 [==============================] - 0s 929us/step - loss: 3.7253e-08
Epoch 203/500
4/4 [==============================] - 0s 849us/step - loss: 5.9605e-08
Epoch 204/500
4/4 [==============================] - 0s 641us/step - loss: 3.7253e-08
Epoch 205/500
4/4 [==============================] - 0s 669us/step - loss: 5.9605e-08
Epoch 206/500
4/4 [==============================] - 0s 637us/step - loss: 3.7253e-08
Epoch 207/500
4/4 [==============================] - 0s 715u

Epoch 293/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 294/500
4/4 [==============================] - 0s 686us/step - loss: 3.7253e-08
Epoch 295/500
4/4 [==============================] - 0s 878us/step - loss: 5.9605e-08
Epoch 296/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 297/500
4/4 [==============================] - 0s 753us/step - loss: 5.9605e-08
Epoch 298/500
4/4 [==============================] - 0s 921us/step - loss: 3.7253e-08
Epoch 299/500
4/4 [==============================] - 0s 999us/step - loss: 5.9605e-08
Epoch 300/500
4/4 [==============================] - 0s 730us/step - loss: 3.7253e-08
Epoch 301/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 302/500
4/4 [==============================] - 0s 2ms/step - loss: 3.7253e-08
Epoch 303/500
4/4 [==============================] - 0s 739us/step - loss: 5.9605e-08
Epoch 304/500
4/4 [==============================] - 0s 1ms/st

Epoch 390/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 391/500
4/4 [==============================] - 0s 873us/step - loss: 5.9605e-08
Epoch 392/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 393/500
4/4 [==============================] - 0s 2ms/step - loss: 5.9605e-08
Epoch 394/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 395/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 396/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 397/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 398/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 399/500
4/4 [==============================] - 0s 838us/step - loss: 5.9605e-08
Epoch 400/500
4/4 [==============================] - 0s 960us/step - loss: 3.7253e-08
Epoch 401/500
4/4 [==============================] - 0s 2ms/step - los

Epoch 487/500
4/4 [==============================] - 0s 798us/step - loss: 5.9605e-08
Epoch 488/500
4/4 [==============================] - 0s 2ms/step - loss: 3.7253e-08
Epoch 489/500
4/4 [==============================] - 0s 838us/step - loss: 5.9605e-08
Epoch 490/500
4/4 [==============================] - 0s 2ms/step - loss: 3.7253e-08
Epoch 491/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 492/500
4/4 [==============================] - 0s 1ms/step - loss: 3.7253e-08
Epoch 493/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 494/500
4/4 [==============================] - 0s 669us/step - loss: 3.7253e-08
Epoch 495/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 496/500
4/4 [==============================] - 0s 2ms/step - loss: 3.7253e-08
Epoch 497/500
4/4 [==============================] - 0s 1ms/step - loss: 5.9605e-08
Epoch 498/500
4/4 [==============================] - 0s 910us/step - l

In [92]:
model.predict(X[:4])

array([[ 0.7506765 ],
       [ 0.5015873 ],
       [ 0.2648834 ],
       [-0.27060547]], dtype=float32)

In [171]:
X[0].shape[0]

6

In [93]:
import numpy as np


In [97]:
a1 = []
a2=[]
out=model.predict(X[:4])
for p in out:
    a1.append(p[0])
for z in Y[:4]:
    a2.append(z[0])
a2 = array(a2)
a1 = array(a1)

In [100]:
np.corrcoef(a1,a2)

array([[1.       , 0.9395043],
       [0.9395043, 1.       ]])

In [102]:
np.mean(out)

0.31163543

In [103]:
np.mean(a2)

0.46595609290486795

In [104]:
np.std(a2)

0.3807917982236212

In [189]:
Y[:4]*data

period       Date  aws_rev     amzn  amzn_rev  gcp_rev  alph_rev  \
0       8  30-Sep-18     6679  2003.00     56580     4640     33740   
1       7  30-Jun-18     6105  1699.80     52890     4425     32657   
2       6  31-Mar-18     5442  1447.34     51040     4354     31146   
3       5  31-Dec-17     5133  1169.47     60500     4687     32323   
4       4  30-Sep-17     4584   961.35     43740     3590     27722   
5       3  30-Jun-17     4100   968.00     37960     3241     26010   
6       2  31-Mar-17     3661   886.54     35710     3207     24750   
7       1  31-Dec-16     3536   749.87     43740     3403     26064   

   azure_rev  msft_rev  
0       8567     29084  
1       9606     30085  
2       7896     26819  
3       7795     28918  
4       6922     24538  
5       7822     25605  
6       6730     23212  
7       6758     25826

In [109]:
acc1= model.predict(X[4:])

In [133]:
acc1 = ((acc1)+1)*(max(data['aws_rev']-min(data['aws_rev'])))+min(data['aws_rev'])


In [142]:
np.std(ac2-array(data['aws_rev'][4:]))*1.96

806.7807821347188

In [139]:
np.mean(array(data['aws_rev'][4:]))

3970.25

In [159]:
np.abs(np.mean((a1-a2)/a2))/(806.7807821347188/3970.25/1.96)

0.5780727505705865

In [160]:
np.mean((a1-a2)/a2)

-0.05993273772613738

In [152]:
a2 = ((a2)+1)*(max(data['aws_rev']-min(data['aws_rev'])))+min(data['aws_rev'])

In [134]:
ac2=[]
for d in acc1:
    ac2.append(d[0])

In [135]:
ac2=array(ac2)

In [177]:
gmean([6,1])

2.449489742783178